var movies = [
  {
    "name": "20thCenturyWomen",
    "posterImage": "images/20thcwomen.jpg", 
    "movieTitle": "20th Century Women",
    "tags": "strong female lead, uplifting, ",
    "rtRating": 98,
    "myRating": 10,
    "synopsis": "Synopsis of movie goes here.",
    "review": "This is the place where I say something eloquent and profound in an attempt to convince you that you too should see this wonderful movie!",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2017,
    "trailer": "https://www.youtube.com/watch?v=p9j8RGTqju0"
  },
     {
    "name": "Elle",
    "posterImage": "images/elle.jpg",
    "movieTitle": "Elle",
    "tags": "strong female lead, psychological thriller",
    "rtRating": 98,
    "myRating": 10,
    "synopsis": "Synopsis of movie goes here.",
    "review": "This is the place where I say something eloquent and profound in an attempt to convince you that you too should see this wonderful movie!",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2017  
  },
      {
    "name": "ManchesterbytheSea",
    "posterImage": "images/mansea.jpg",
    "movieTitle": "Manchester By the Sea",
    "tags": "sad",
    "rtRating": 98,
    "myRating": 8,
    "synopsis": "Synopsis of movie goes here.",
    "review": "This is the place where I say something eloquent and profound in an attempt to convince you that you too should see this wonderful movie!",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2016  
  },
       {
    "name": "13th",
    "posterImage": "images/13th.jpg",
    "movieTitle": "13th",
    "tags": "",
    "rtRating": 97,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "This is the place where I say something eloquent and profound in an attempt to convince you that you too should see this wonderful movie!",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2016  
  },
        {
    "name": "Arrival",
    "posterImage": "images/arrival.jpg",
    "movieTitle": "Arrival",
    "tags": "",
    "rtRating": 94,
    "myRating": 8.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "This is the place where I say something eloquent and profound in an attempt to convince you that you too should see this wonderful movie!",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2003 
  },
        {
    "name": "CaptainFantastic",
    "posterImage": "images/capfan.jpg",
    "movieTitle": "Captain Fantastic",
    "tags": "",
    "rtRating": 83,
    "myRating": 7.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "This is the place where I say something eloquent and profound in an attempt to convince you that you too should see this wonderful movie!",
    "recommendations": "If you like this watch...",
    "platform": "Amazon Prime",
    "releasedate": 2007 
  },
        {
    "name": "Colossal",
    "posterImage": "images/colossal.jpg",
    "movieTitle": "Colassal",
    "tags": "",
    "rtRating": 76,
    "myRating": 8.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "This is the place where I say something eloquent and profound in an attempt to convince you that you too should see this wonderful movie!",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2019 
            
  },
        {
    "name": "ExMachina",
    "posterImage": "images/exmac.jpg",
    "movieTitle": "Ex Machina",
    "tags": "",
    "rtRating": 93,
    "myRating": 10,
    "synopsis": "Synopsis of movie goes here.",
    "review": "Modern Day Frankenstein. Alicia Vikander. Shit. ",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1970 
  },
        {
    "name": "Fences",
    "posterImage": "images/fences.jpg",
    "movieTitle": "Fences",
    "tags": "",
    "rtRating": 93,
    "myRating": 9,
    "synopsis": "Synopsis of movie goes here.",
    "review": "Modern Day Frankenstein. Alicia Vikander. Shit. ",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1980 
            
  },
        {
    "name": "FlorenceFosterJenkins",
    "posterImage": "images/ffj.jpg",
    "movieTitle": "Florence Foster Jenkins",
    "tags": "",
    "rtRating": 87,
    "myRating": 7.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2003       
  },       
        {
    "name": "FrancesHa",
    "posterImage": "images/francesha.jpg",
    "movieTitle": "Frances Ha",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2005 
  },
      {
    "name": "GetOut",
    "posterImage": "images/getout.jpg",
    "movieTitle": "Get Out",
    "tags": "",
    "rtRating": 99,
    "myRating": 10,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1998
  },
    
        {
    "name": "HacksawRidge",
    "posterImage": "images/hacksaw.jpg",
    "movieTitle": "Hacksaw Ridge",
    "tags": "",
    "rtRating": 87,
    "myRating": 8,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2000
  },
        {
    "name": "HelloMyNameisDoris",
    "posterImage": "images/hellomynameisdoris.jpg",
    "movieTitle": "Hello My Name is Doris",
    "tags": "",
    "rtRating": 83,
    "myRating": 7.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2017 
  },
        {
    "name": "HellorHighWater",
    "posterImage": "images/hellorhighwater.jpg",
    "movieTitle": "Hell or High Water",
    "tags": "",
    "rtRating": 98,
    "myRating": 8.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2016 
  },
        {
    "name": "HiddenFigures",
    "posterImage": "images/hiddenfigures.jpg",
    "movieTitle": "Hidden Figures",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 2016  
  },
           {
    "name": "Goodwillhunting",
    "posterImage": "images/goodwillhunting.jpg",
    "movieTitle": "Good Will Hunting",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
              {
    "name": "Jackie",
    "posterImage": "images/jackie.jpg",
    "movieTitle": "Jackie",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
                  {
    "name": "Joshy",
    "posterImage": "images/joshy.jpg",
    "movieTitle": "Joshy",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
                  {
    "name": "Krisha",
    "posterImage": "images/krisha.jpg",
    "movieTitle": "Krisha",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
                  {
    "name": "LaLaLand",
    "posterImage": "images/lalaland.jpeg",
    "movieTitle": "La La Land",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
                  {
    "name": "Life,Animated",
    "posterImage": "images/lifeanimated.jpg",
    "movieTitle": "Life, Animated",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "Lion",
    "posterImage": "images/lion.jpg",
    "movieTitle": "Lion",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
    
        {
    "name": "Littlemen",
    "posterImage": "images/littlemen.jpg",
    "movieTitle": "Little Men",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "Loving",
    "posterImage": "images/loving.jpg",
    "movieTitle": "Loving",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "Moana",
    "posterImage": "images/moana.jpg",
    "movieTitle": "Moana",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "Moonlight",
    "posterImage": "images/moonlight.jpg",
    "movieTitle": "Moonlight",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "OtherPeople",
    "posterImage": "images/otherpeople.jpg",
    "movieTitle": "Other People",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "SingStreet",
    "posterImage": "images/singstreet.jpg",
    "movieTitle": "Sing Street",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997
  },
           {
    "name": "Paddington",
    "posterImage": "images/goodwillhunting.jpg",
    "movieTitle": "Good Will Hunting",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
         {
    "name": "Sightseers",
    "posterImage": "images/goodwillhunting.jpg",
    "movieTitle": "Good Will Hunting",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "Thebigask",
    "posterImage": "images/goodwillhunting.jpg",
    "movieTitle": "Good Will Hunting",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "Theimitationgame",
    "posterImage": "images/goodwillhunting.jpg",
    "movieTitle": "The Imitation Game",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "Theintervention",
    "posterImage": "images/intervention.jpg",
    "movieTitle": "The Intervention",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "Thejunglebook",
    "posterImage": "images/junglebook.jpg",
    "movieTitle": "The Jungle Book",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
        {
    "name": "Thelobster",
    "posterImage": "images/lobster.jpg",
    "movieTitle": "The Lobster",
    "tags": "",
    "rtRating": 93,
    "myRating": 9.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "",
    "recommendations": "If you like this watch...",
    "platform": "",
    "releasedate": 1997  
  },
  {
    "name": "Winitall",
    "posterImage": "images/winit.jpg",
    "movieTitle": "Win It All",
    "tags": "Joe Swanberg, Jake Johnson, Joe Lo Truglia",
    "rtRating": 93,
    "myRating": 8.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "Another classic Swanberg film. Examines the addictive and detrimental impact of gambling. Enjoyed allusion to 'The Hustler' and Fast Eddie.",
    "recommendations": "Happy Christmas, Drinking Buddies",
    "platform": "Netflix",
    "releasedate": 2017  
  },
    {
    "name": "Happy Christmas",
    "posterImage": "images/winit.jpg",
    "movieTitle": "Win It All",
    "tags": "Joe Swanberg, Anna Kendrick",
    "rtRating": 93,
    "myRating": 8.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "Swanberg is at it again. Get ready to watch your favorite characters stumble, you'll find yourself wincing and rooting for Eddie along the way. Examines the addictive and detrimental impact of gambling. Enjoyed allusion to 'The Hustler' and Fast Eddie.",
    "recommendations": "Happy Christmas, Drinking Buddies",
    "platform": "Netflix",
    "releasedate": 2017  
  },
      {
    "name": "Drinking Buddies",
    "posterImage": "images/winit.jpg",
    "movieTitle": "Drinking Buddies",
    "tags": "Joe Swanberg, Jake Johnson, Olivia Wilde, Anna Kendrick, ",
    "rtRating": 93,
    "myRating": 6.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "Another classic Swanberg film. Examines the addictive and detrimental impact of gambling. Enjoyed allusion to 'The Hustler' and Fast Eddie.",
    "recommendations": "Happy Christmas, Drinking Buddies",
    "platform": "Netflix",
    "releasedate": 2017  
  },
  {
    "name": "Happy Christmas",
    "posterImage": "images/happyxmas.jpg",
    "movieTitle": "Happy Christmas",
    "tags": "Joe Swanberg, Anna Kendrick, Melanie Lynksy",
    "rtRating": 93,
    "myRating": 6.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "Swanberg's sweet spot is creating character's . Examines the addictive and detrimental impact of gambling. Enjoyed allusion to 'The Hustler' and Fast Eddie.",
    "recommendations": "Win It All, Drinking Buddies",
    "platform": "Netflix",
    "releasedate": 2017  
  },
    {
    "name": "A League of Their Own",
    "posterImage": "images/leagueofown.jpg",
    "movieTitle": "Happy Christmas",
    "tags": "Joe Swanberg, Anna Kendrick, Melanie Lynksy",
    "rtRating": 93,
    "myRating": 6.5,
    "synopsis": "Synopsis of movie goes here.",
    "review": "Swanberg's sweet spot is creating character's . Examines the addictive and detrimental impact of gambling. Enjoyed allusion to 'The Hustler' and Fast Eddie.",
    "recommendations": "Win It All, Drinking Buddies",
    "platform": "Netflix",
    "releasedate": 2017  
  },
    
];

